apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: springboot-app-svc
spec:
  hosts:
    - springboot-app-svc.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: springboot-app-svc.default.svc.cluster.local
        subset: v1
      weight: 100
    mirror:
      host: springboot-app-svc.default.svc.cluster.local
      subset: v2
    mirrorPercent: 100