apiVersion: v1
kind: Service
metadata:
  name: python-app-anticaptcha-svc
  labels:
    app: python-app-anticaptcha
    service: python-app-anticaptcha
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: python-app-anticaptcha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-anticaptcha-v1
  labels:
    app: python-app-anticaptcha
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-anticaptcha
      version: v1
  template:
    metadata:
      labels:
        app: python-app-anticaptcha
        version: v1
    spec:
      containers:
      - name: python-app-anticaptcha
        image: anticaptcha:0.0.2
        command: [ "/bin/bash","-c","cd /root/projects/antiCaptcha;/opt/conda/envs/antiCaptcha/bin/python /root/projects/antiCaptcha/run.py" ]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 18080
        securityContext:
          runAsUser: 1000
---