apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-v2
  labels:
    app: springboot-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
      version: v2
  template:
    metadata:
      labels:
        app: springboot-app
        version: v2
    spec:
      containers:
      - name: springboot-app
        image: wardenlym/springboot-app:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1000
---